In [13]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.feature_extraction.text import CountVectorizer

In [14]:
df=pd.read_csv('sentiment_analysis.csv')
df.head()

,Year,Month,Day,Time of Tweet,text,sentiment,Platform
0,2018,8,18,morning,What a great day!!! Looks like dream.,positive,Twitter
1,2018,8,18,noon,"I feel sorry, I miss you here in the sea beach",positive,Facebook
2,2017,8,18,night,Don't angry me,negative,Facebook
3,2022,6,8,morning,We attend in the class just for listening teac...,negative,Facebook
4,2022,6,8,noon,"Those who want to go, let them go",negative,Instagram

In [15]:
x=df['text']
y=df.sentiment

In [16]:
xtrain, xtest, ytrain, ytest = train_test_split(x,y,random_state=42, train_size=0.8)

In [17]:
vectorizer=CountVectorizer(stop_words='english')

In [18]:
values=vectorizer.fit_transform(xtrain)

In [19]:
values=values.toarray()

In [20]:
cols=vectorizer.get_feature_names_out()

In [21]:
pd.DataFrame(data=values, columns=cols)

,00,10,100,11,140,15,1750,19,20,21,...,yea,yeah,years,yep,yes,yesterday,yor,youtube,yum,zero
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
395,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
396,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
397,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
398,0,1,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0

In [22]:
xtest.shape

(100,)

In [23]:
vectorizer.transform(xtest)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 342 stored elements and shape (100, 1101)>