# Encoding techniques 
- ### LabelEncoder
- ### OneHotEncoder
- ### OrdinalEncoder
- ### TargetEncoder

In [1]:
import pandas as pd 
import numpy as np 
# np.random()
n_rows=1000
data={'color':np.random.choice(['red','blue','green'],n_rows),
      'size': np.random.choice(['small','medium','large'],n_rows),
      'material':np.random.choice(['plastic','metal','wood'],n_rows),
      'price': np.random.randint(10,500,n_rows)}
df=pd.DataFrame(data)

In [2]:
df

     color    size material  price
0    green   small     wood     37
1      red  medium     wood    188
2    green   small    metal    286
3    green   small  plastic    466
4     blue  medium     wood     91
..     ...     ...      ...    ...
995    red  medium  plastic    227
996   blue  medium     wood    370
997   blue   large    metal    389
998  green   small    metal     48
999   blue  medium    metal    448

[1000 rows x 4 columns]

### - Importing all the encoding preprocessing modules from sklearn

In [3]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from category_encoders import TargetEncoder

In [4]:
X=df.drop(columns='price')
Y=df['price']
Xtrain,Xtest,Ytrain,Ytest=train_test_split(X,Y,train_size=0.8,random_state=42)

- # LabelEncoder

In [5]:
label_encoder=LabelEncoder()
'''updated_xtrain=label_encoder.fit_transform(Xtrain)
ValueError("y should be a 1d array, got an array of shape {} instead.".format(shape))
   '''

'updated_xtrain=label_encoder.fit_transform(Xtrain)\nValueError("y should be a 1d array, got an array of shape {} instead.".format(shape))\n   '

In [6]:
label_encoder.fit_transform(Xtrain['color'])

array([1, 0, 1, 0, 0, 1, 2, 1, 2, 2, 2, 0, 2, 2, 2, 1, 0, 0, 1, 2, 1, 1,
       1, 0, 0, 1, 2, 2, 1, 0, 1, 1, 2, 1, 0, 2, 1, 2, 2, 2, 1, 0, 0, 1,
       2, 1, 0, 0, 1, 2, 2, 1, 0, 2, 2, 1, 2, 0, 1, 2, 2, 2, 0, 1, 2, 1,
       0, 2, 1, 0, 2, 2, 1, 1, 1, 0, 0, 2, 0, 2, 2, 1, 1, 0, 2, 1, 1, 1,
       2, 0, 2, 2, 2, 0, 1, 0, 1, 2, 1, 0, 2, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       2, 1, 0, 2, 2, 2, 2, 2, 2, 0, 0, 1, 0, 0, 1, 2, 1, 2, 0, 1, 1, 2,
       1, 2, 1, 0, 0, 2, 1, 2, 0, 0, 2, 1, 1, 0, 1, 2, 2, 2, 0, 1, 1, 2,
       2, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 2, 0, 2, 2, 0, 2, 2, 0, 0, 1, 2,
       2, 1, 0, 2, 2, 2, 0, 0, 0, 1, 2, 0, 2, 2, 2, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 2, 1, 0, 1, 2, 2, 2, 1, 0, 2, 0, 1, 1, 0, 2, 2, 2, 0, 2,
       1, 0, 0, 1, 1, 1, 0, 2, 1, 0, 1, 2, 0, 1, 0, 1, 2, 0, 1, 2, 0, 0,
       1, 1, 1, 1, 2, 0, 1, 1, 2, 0, 2, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       2, 1, 2, 0, 0, 2, 1, 2, 0, 2, 2, 0, 0, 1, 2, 2, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 2, 0, 2, 0, 1, 0, 2, 0, 2, 1, 1, 2, 1, 0, 2, 1, 1, 0, 1,
       0, 0, 1, 0, 2, 2, 0, 2, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       2, 1, 1, 0, 2, 0, 2, 2, 0, 1, 1, 1, 0, 2, 0, 0, 1, 0, 2, 0, 0, 0,
       2, 0, 1, 1, 2, 0, 0, 0, 2, 0, 0, 0, 2, 1, 2, 2, 0, 2, 1, 0, 2, 0,
       0, 1, 2, 2, 0, 2, 0, 0, 2, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 2, 2, 2,
       1, 1, 1, 1, 2, 0, 0, 1, 2, 0, 1, 1, 1, 0, 2, 2, 2, 0, 1, 1, 0, 0,
       0, 1, 0, 2, 1, 0, 1, 0, 0, 1, 1, 1, 0, 2, 0, 1, 1, 0, 2, 2, 0, 2,
       2, 1, 0, 1, 0, 0, 1, 1, 0, 0, 2, 0, 0, 0, 1, 2, 1, 1, 0, 0, 0, 0,
       2, 2, 2, 0, 2, 1, 2, 2, 0, 1, 2, 1, 0, 1, 2, 1, 1, 0, 0, 1, 1, 1,
       2, 1, 2, 1, 1, 1, 0, 0, 0, 2, 0, 1, 2, 2, 0, 1, 0, 0, 0, 0, 1, 2,
       2, 1, 2, 2, 1, 1, 2, 0, 1, 1, 1, 0, 0, 0, 2, 2, 1, 0, 2, 0, 2, 1,
       2, 0, 0, 2, 0, 2, 1, 2, 2, 0, 0, 0, 2, 0, 0, 1, 2, 0, 2, 2, 2, 2,
       0, 2, 1, 2, 2, 1, 2, 2, 0, 0, 1, 1, 2, 0, 1, 1, 0, 0, 0, 0, 2, 0,
       2, 2, 2, 0, 1, 2, 2, 0, 2, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 2, 1,
       0, 2, 2, 1, 2, 2, 1, 2, 1, 1, 0, 1, 0, 1, 1, 1, 2, 0, 0, 2, 1, 0,
       0, 1, 0, 2, 1, 2, 0, 2, 1, 0, 0, 1, 1, 1, 2, 1, 0, 0, 0, 0, 0, 0,
       0, 2, 2, 1, 2, 1, 0, 0, 1, 0, 2, 2, 2, 1, 2, 0, 2, 0, 2, 1, 2, 2,
       0, 1, 0, 2, 1, 2, 2, 2, 2, 2, 1, 0, 1, 0, 0, 0, 0, 0, 2, 1, 2, 1,
       1, 0, 0, 2, 0, 2, 1, 2, 2, 2, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       2, 2, 0, 1, 0, 2, 1, 0, 2, 2, 2, 2, 0, 0, 1, 2, 2, 2, 2, 0, 2, 1,
       0, 2, 1, 1, 2, 1, 1, 2, 1, 1, 0, 2, 1, 2, 1, 2, 1, 2, 0, 2, 2, 2,
       0, 0, 1, 1, 2, 0, 0, 1, 0, 1, 2, 2, 1, 1, 0, 2, 2, 0, 0, 2, 0, 0,
       2, 0, 2, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 2, 1, 0, 2, 1, 2, 2, 0,
       2, 1, 2, 0, 2, 2, 0, 0])

- # OneHotEncoder

In [7]:
one_hot_encoder=OneHotEncoder(sparse_output=False)
# one_hot_encoder.fit_transform(Xtrain)
values=one_hot_encoder.fit_transform(Xtrain)
# values=values.toarray()
values

array([[0., 1., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 1., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 1.]])

In [8]:
columns=one_hot_encoder.get_feature_names_out()

In [9]:
pd.DataFrame(values,columns=columns).astype(int)

,color_blue,color_green,color_red,size_large,size_medium,size_small,material_metal,material_plastic,material_wood
0,0,1,0,0,0,1,1,0,0
1,1,0,0,0,0,1,1,0,0
2,0,1,0,0,1,0,0,1,0
3,1,0,0,1,0,0,0,0,1
4,1,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...
795,1,0,0,1,0,0,0,0,1
796,0,0,1,0,1,0,0,1,0
797,0,0,1,0,1,0,1,0,0
798,1,0,0,0,1,0,0,0,1
799,1,0,0,0,1,0,0,0,1

In [10]:
'''one_hot_encoder.transform(Xtest['color'])  Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead'''
'''one_hot_encoder.transform(Xtest[['color','size']]) ValueError: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- material
'''

"one_hot_encoder.transform(Xtest[['color','size']]) ValueError: The feature names should match those that were passed during fit.\nFeature names seen at fit time, yet now missing:\n- material\n"

In [11]:
'''
new_input=[['red','large'],['blue','small']]
one_hot_encoder.transform(new_input)  #ValueError: X has 2 features, but OneHotEncoder is expecting 3 features as input.
'''

'''new_input=[['red1','large','plastic'],['blue','small','wood']]
one_hot_encoder.transform(new_input)
ValueError: Found unknown categories ['red1'] in column 0 during transform
'''

"new_input=[['red1','large','plastic'],['blue','small','wood']]\none_hot_encoder.transform(new_input)\nValueError: Found unknown categories ['red1'] in column 0 during transform\n"

In [12]:
one_hot_encoder=OneHotEncoder(sparse_output=False,  handle_unknown='ignore')
updated_xtrain=one_hot_encoder.fit_transform(Xtrain)
new_input=[['red1','large','plastic'],['blue','small','wood']]
one_hot_encoder.transform(new_input)

c:\Users\91789\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[0., 0., 0., 1., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 1., 0., 0., 1.]])

- if label is not present then it assigns zero - for this we need to use handle_unknown='ignore'(By default it will be 'error') It ignores the errors

In [13]:
one_hot_encoder.get_feature_names_out()

array(['color_blue', 'color_green', 'color_red', 'size_large',
       'size_medium', 'size_small', 'material_metal', 'material_plastic',
       'material_wood'], dtype=object)

- # OrdinalEncoder

In [14]:
from sklearn.preprocessing import OrdinalEncoder

In [15]:
Ordi_encoder=OrdinalEncoder()
Ordi_encoder.fit_transform(Xtrain)


'''Ordi_encoder.fit_transform(Xtrain['color']) 
Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead.
Pass a DataFrame containing a single row.
'''
'''Ordi_encoder.transform(Xtest['color'])
'Ordi_encoder.fit_transform(Xtest['color']) 
Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead.
Pass a DataFrame containing a single row.'''

"Ordi_encoder.transform(Xtest['color'])\n'Ordi_encoder.fit_transform(Xtest['color']) \nExpected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead.\nPass a DataFrame containing a single row."

In [16]:
Ordi_encoder.get_feature_names_out()

array(['color', 'size', 'material'], dtype=object)

In [17]:
'''
new_input=[['gold','medium','metal']]
Ordi_encoder.transform(new_input)
ValueError: Found unknown categories ['gold'] in column 0 during transform'''

"\nnew_input=[['gold','medium','metal']]\nOrdi_encoder.transform(new_input)\nValueError: Found unknown categories ['gold'] in column 0 during transform"

In [18]:
ord_encoder=OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)

In [19]:

ord_encoder.fit_transform(Xtrain)
new_input=[['gold','medium','metal'], ['red','large','wood']]
ord_encoder.transform(new_input)

c:\Users\91789\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[-1.,  1.,  0.],
       [ 2.,  0.,  2.]])

In [20]:
# to remove the warning in the above cell
new_data=pd.DataFrame(data=[['gold','medium','metal'], ['red','large','wood']], columns=['color','size','material'])
ord_encoder.transform(new_data)

array([[-1.,  1.,  0.],
       [ 2.,  0.,  2.]])

In [21]:
'''o_encoder=OrdinalEncoder(categories=[['green','blue','red']],handle_unknown='use_encoded_value',unknown_value=-1)
o_encoder.fit_transform(Xtrain) 
#ValueError: Shape mismatch: if categories is an array, it has to be of shape (n_features,)
Here we have passed only one column order but we have to mention all columns order or else it will throw value error due to shape mismatch.
'''

"o_encoder=OrdinalEncoder(categories=[['green','blue','red']],handle_unknown='use_encoded_value',unknown_value=-1)\no_encoder.fit_transform(Xtrain) \n#ValueError: Shape mismatch: if categories is an array, it has to be of shape (n_features,)\nHere we have passed only one column order but we have to mention all columns order or else it will throw value error due to shape mismatch.\n"

In [22]:
o_encoder=OrdinalEncoder(categories=[['green','blue','red'],['medium','small','large'],['wood','plastic','metal']],
                         handle_unknown='use_encoded_value',unknown_value=-1) # here all columns order have been mentioned so it works properly
o_encoder.fit_transform(Xtrain)
o_encoder.transform(Xtest)
new_input=pd.DataFrame([['red','small','metal']],columns=Xtrain.columns)
o_encoder.transform(new_input) #array([[2., 1., 2.]]) # transform also accepts 2D.
# so it is arranging based on the order .

array([[2., 1., 2.]])

In [23]:
o_encoder=OrdinalEncoder(categories=[['green1','blue','red'],['medium','small','large'],['wood','plastic','metal']],
                         handle_unknown='use_encoded_value',unknown_value=-1) 
# when we are passing unknown value in the categories order it assigns -1 for the value which we have not mentioned 
o_encoder.fit_transform(Xtrain)

array([[-1.,  1.,  2.],
       [ 1.,  1.,  2.],
       [-1.,  0.,  1.],
       ...,
       [ 2.,  0.,  2.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.]])

In [24]:
'''o_encoder=OrdinalEncoder(categories=[['green1','blue','red'],['wood','plastic','metal'],['medium','small','large']])
o_encoder.fit_transform(Xtrain) 
#ValueError: Found unknown categories ['green'] in column 0 during fit'''

"o_encoder=OrdinalEncoder(categories=[['green1','blue','red'],['wood','plastic','metal'],['medium','small','large']])\no_encoder.fit_transform(Xtrain) \n#ValueError: Found unknown categories ['green'] in column 0 during fit"

In [25]:
'''o_encoder=OrdinalEncoder(categories=[['green1','blue','red'],['wood','plastic','metal'],['medium','small','large']], handle_unknown='use_encoded_value')
o_encoder.fit_transform(Xtrain) 
#TypeError: unknown_value should be an integer or np.nan when handle_unknown is 'use_encoded_value', got None.'''

"o_encoder=OrdinalEncoder(categories=[['green1','blue','red'],['wood','plastic','metal'],['medium','small','large']], handle_unknown='use_encoded_value')\no_encoder.fit_transform(Xtrain) \n#TypeError: unknown_value should be an integer or np.nan when handle_unknown is 'use_encoded_value', got None."

- # TargetEncoder

In [26]:
from category_encoders import TargetEncoder
t_encoder=TargetEncoder(cols='color', handle_unknown='values') 
#we can use this cols parameter when we have mixed columns 
#handle_unkown solves the error, when we have unknown values then, it will transform by finding the average of all the target columns (ytrain)

In [27]:
'''t_encoder.fit_transform(Xtrain) #TypeError: fit_transform() missing argument: y'''

't_encoder.fit_transform(Xtrain) #TypeError: fit_transform() missing argument: y'

In [28]:
t_encoder.fit_transform(Xtrain,Ytrain) 
#when we have more unique values we can use this target encoder and we apply this for only categorical columns

          color    size material
29   248.207692   small    metal
535  250.996429   small    metal
695  248.207692  medium  plastic
557  250.996429   large     wood
836  250.996429   large     wood
..          ...     ...      ...
106  250.996429   large     wood
270  258.284615  medium  plastic
860  258.284615  medium    metal
435  250.996429  medium     wood
102  250.996429  medium     wood

[800 rows x 3 columns]

In [29]:
obj_cols=Xtrain.select_dtypes(include='object')
#to select particular type of column which is required like for example here 
# above we have used include paramenter inside select_dtypes to include only the object columns.
num_cols=Xtrain.select_dtypes(include='int')
obj_cols

     color    size material
29   green   small    metal
535   blue   small    metal
695  green  medium  plastic
557   blue   large     wood
836   blue   large     wood
..     ...     ...      ...
106   blue   large     wood
270    red  medium  plastic
860    red  medium    metal
435   blue  medium     wood
102   blue  medium     wood

[800 rows x 3 columns]

In [30]:
t_encoder.transform(Xtest)

          color    size material
521  250.996429   small  plastic
737  250.996429   large     wood
740  248.207692   large  plastic
660  248.207692   small    metal
411  258.284615  medium  plastic
..          ...     ...      ...
408  250.996429   small  plastic
332  258.284615   small  plastic
208  250.996429   small    metal
613  258.284615   small     wood
78   258.284615   large  plastic

[200 rows x 3 columns]

In [31]:
# new_input=[['red','medium','metal']]
#KeyError: 'color' , it returns key error because we need to pass the new values along with the column names also 
# t_encoder.transform(new_input)

In [ ]:
new_input = pd.DataFrame([['red', 'medium', 'metal']],columns=Xtrain.columns)
# new_input=pd.DataFrame({'color':['red'],'size':['medium'],'material':['wood']})
# Both of the ways are correct , we can use any one

In [33]:
t_encoder.transform(new_input)

        color    size material
0  258.284615  medium     wood