In [22]:
import pandas as pd

In [23]:
df=pd.read_csv('energy_data.csv')
df

,Square Footage,Number of Occupants,Appliances Used,Average Temperature,Energy Consumption
0,7063,76,10,29.84,2713.95
1,44372,66,45,16.72,5744.99
2,19255,37,17,14.30,4101.24
3,13265,14,41,32.82,3009.14
4,13375,26,18,11.92,3279.17
...,...,...,...,...,...
995,14419,68,44,23.95,3661.21
996,12194,7,22,14.67,3546.34
997,39562,88,20,32.18,5147.21
998,8348,67,37,16.48,3244.98
999,15813,57,11,31.40,3423.63

In [24]:
df.columns

Index(['Square Footage', 'Number of Occupants', 'Appliances Used',
       'Average Temperature', 'Energy Consumption'],
      dtype='object')

In [25]:
df.corr()

,Square Footage,Number of Occupants,Appliances Used,Average Temperature,Energy Consumption
Square Footage,1.000000,0.033379,-0.013478,0.027273,0.774873
Number of Occupants,0.033379,1.000000,0.023646,0.014122,0.354485
Appliances Used,-0.013478,0.023646,1.000000,-0.062870,0.312792
Average Temperature,0.027273,0.014122,-0.062870,1.000000,-0.034487
Energy Consumption,0.774873,0.354485,0.312792,-0.034487,1.000000

In [26]:
df=df.drop(columns=['Average Temperature'])

In [27]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_absolute_error,root_mean_squared_error

In [28]:
x=df[['Square Footage', 'Number of Occupants', 'Appliances Used']]
y=df['Energy Consumption']

In [29]:
model=LinearRegression()

In [30]:
X_train,X_test,Y_train,Y_test=train_test_split(x,y,train_size=0.8,random_state=42)

In [31]:
model.fit(X_train,Y_train)

LinearRegression()

In [32]:
ypred_train=model.predict(X_train)
score=r2_score(Y_train,ypred_train)
score

0.8110292227860276

In [33]:
mae=mean_absolute_error(Y_train,ypred_train)
mae

347.38324221437426

In [34]:
rmse=root_mean_squared_error(Y_train,ypred_train)
rmse

408.37179268356863

In [35]:
ypred_test=model.predict(X_test)
score1=r2_score(Y_test,ypred_test)
score1

0.7903977691386851

In [36]:
mae1=mean_absolute_error(Y_test,ypred_test)
mae1

345.0742613941109

In [37]:
rmse1=root_mean_squared_error(Y_test,ypred_test)
rmse1

413.13334485452964

- As the values of MAE and RMSE are far so the model has failed to capture the outliers

In [38]:
from sklearn.preprocessing import StandardScaler, RobustScaler, MinMaxScaler
scaler=StandardScaler()
u_train=scaler.fit_transform(X_train)
u_test=scaler.fit_transform(X_test)

In [39]:
scaler1=RobustScaler()
u_train=scaler1.fit_transform(X_train)
u_test=scaler1.transform(X_test)

In [41]:
scaler2=MinMaxScaler()
u_train=scaler2.fit_transform(X_train)
u_test=scaler2.transform(X_test)