In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from category_encoders import TargetEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

In [2]:
df=pd.read_csv('Spotify_Music.csv')
df.head()

,slno,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,...,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,...,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,acoustic
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,...,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,acoustic
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,...,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,...,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic

In [3]:
df.drop(columns=['track_id', 'album_name', 'track_name'],inplace=True)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114000 entries, 0 to 113999
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   slno              114000 non-null  int64
 1   artists           113999 non-null  object
 2   popularity        114000 non-null  int64
 3   duration_ms       114000 non-null  int64
 4   explicit          114000 non-null  bool
 5   danceability      114000 non-null  float64
 6   energy            114000 non-null  float64
 7   key               114000 non-null  int64
 8   loudness          114000 non-null  float64
 9   mode              114000 non-null  int64
 10  speechiness       114000 non-null  float64
 11  acousticness      114000 non-null  float64
 12  instrumentalness  114000 non-null  float64
 13  liveness          114000 non-null  float64
 14  valence           114000 non-null  float64
 15  tempo             114000 non-null  float64
 16  time_signature    114000 non-null  int64
 17  track_genre       114000 non-null  object
dtypes: bool(1), float64(9), int64(6), object(2)
memory usage: 14.9+ MB

In [5]:
df.isnull().any()

slno                False
artists              True
popularity          False
duration_ms         False
explicit            False
danceability        False
energy              False
key                 False
loudness            False
mode                False
speechiness         False
acousticness        False
instrumentalness    False
liveness            False
valence             False
tempo               False
time_signature      False
track_genre         False
dtype: bool

In [6]:
df[df.isnull().any(axis=1)]

,slno,artists,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
65900,65900,NaN,0,0,False,0.501,0.583,7,-9.46,0,0.0605,0.69,0.00396,0.0747,0.734,138.391,4,k-pop

In [7]:
df.dropna(inplace=True)

In [8]:
df.drop(columns='slno',inplace=True)

In [9]:
x=df.drop(columns='track_genre')
y=df.track_genre

In [10]:
obj_cols=x.select_dtypes(include='object').columns
obj_cols

Index(['artists'], dtype='object')

In [11]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,train_size=0.8,random_state=42)

In [12]:
x[obj_cols].nunique()

artists    31437
dtype: int64

In [13]:
preprocessing=ColumnTransformer(
    transformers=[
        ('encoder', TargetEncoder(), obj_cols)
    ],
    remainder='passthrough'
)

In [14]:
main_pipeline=Pipeline(
    steps=[
        ('preprocessing',preprocessing),
        ('model',RandomForestClassifier(n_estimators=150, max_depth=25, min_samples_leaf=5, random_state=42))
    ]
)

In [15]:
main_pipeline.fit(xtrain,ytrain)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('encoder', TargetEncoder(),
                                                  Index(['artists'], dtype='object'))])),
                ('model',
                 RandomForestClassifier(max_depth=25, min_samples_leaf=5,
                                        n_estimators=150, random_state=42))])

In [16]:
ypred_train=main_pipeline.predict(xtrain)

In [17]:
print(classification_report(ytrain, ypred_train))

                   precision    recall  f1-score   support

         acoustic       0.77      0.89      0.83       787
         afrobeat       0.89      0.95      0.92       797
         alt-rock       0.49      0.48      0.49       785
      alternative       0.48      0.53      0.50       816
          ambient       0.76      0.83      0.79       803
            anime       0.74      0.85      0.79       807
      black-metal       0.88      0.93      0.90       790
        bluegrass       0.87      0.95      0.91       795
            blues       0.60      0.66      0.63       786
           brazil       0.66      0.60      0.63       803
        breakbeat       0.89      0.92      0.90       801
          british       0.78      0.62      0.69       786
         cantopop       0.84      0.94      0.89       807
    chicago-house       0.95      0.94      0.95       794
         children       0.93      0.96      0.94       786
            chill       0.76      0.79      0.77       802
        classical       0.78      0.93      0.85       802
             club       0.93      0.91      0.92       809
           comedy       0.98      0.96      0.97       809
          country       0.81      0.89      0.85       792
            dance       0.64      0.71      0.67       794
        dancehall       0.85      0.83      0.84       796
      death-metal       0.72      0.93      0.81       808
       deep-house       0.72      0.81      0.76       814
   detroit-techno       0.94      0.96      0.95       806
            disco       0.81      0.74      0.77       806
           disney       0.88      0.91      0.90       801
    drum-and-bass       0.95      0.94      0.94       806
              dub       0.68      0.53      0.60       796
          dubstep       0.64      0.76      0.69       774
              edm       0.47      0.49      0.48       800
          electro       0.66      0.52      0.58       793
       electronic       0.86      0.77      0.81       800
              emo       0.79      0.72      0.75       807
             folk       0.72      0.65      0.68       788
            forro       0.84      0.96      0.90       795
           french       0.92      0.83      0.87       806
             funk       0.74      0.70      0.72       782
           garage       0.88      0.81      0.84       808
           german       0.90      0.67      0.77       804
           gospel       0.75      0.86      0.80       788
             goth       0.89      0.81      0.85       777
        grindcore       0.98      0.96      0.97       774
           groove       0.83      0.63      0.72       788
           grunge       0.77      0.87      0.82       798
           guitar       0.88      0.93      0.90       811
            happy       0.85      0.90      0.87       801
        hard-rock       0.64      0.60      0.62       815
         hardcore       0.79      0.82      0.80       795
        hardstyle       0.93      0.95      0.94       790
      heavy-metal       0.89      0.96      0.92       802
          hip-hop       0.80      0.69      0.74       798
       honky-tonk       0.98      0.98      0.98       795
            house       0.51      0.55      0.53       770
              idm       0.96      0.97      0.97       783
           indian       0.74      0.73      0.73       798
            indie       0.65      0.33      0.44       788
        indie-pop       0.63      0.55      0.59       791
       industrial       0.85      0.83      0.84       789
          iranian       0.94      1.00      0.97       819
          j-dance       0.86      0.88      0.87       787
           j-idol       0.89      0.93      0.91       810
            j-pop       0.72      0.55      0.63       776
           j-rock       0.67      0.58      0.62       804
             jazz       0.75      0.67      0.71       787
            k-pop       0.87      0.86      0.87       786
             kids       0.91      0.96      0.93       802
            latin       0.48      0.51      0.49       790
           latino       0.44      0.47      0.45       807
            malay       0.92      0.89      0.91       811
         mandopop       0.90      0.85      0.87       813
            metal       0.54      0.43      0.48       814
        metalcore       0.76      0.82      0.79       794
   minimal-techno       0.73      0.84      0.78       792
              mpb       0.71      0.69      0.70       809
          new-age       0.86      0.91      0.88       801
            opera       0.88      0.86      0.87       811
           pagode       0.77      0.84      0.81       808
            party       0.84      0.91      0.87       795
            piano       0.85      0.74      0.79       803
              pop       0.74      0.63      0.68       834
         pop-film       0.74      0.85      0.79       787
        power-pop       0.86      0.86      0.86       777
progressive-house       0.79      0.78      0.78       809
       psych-rock       0.72      0.66      0.69       804
             punk       0.58      0.54      0.56       779
        punk-rock       0.58      0.59      0.59       808
            r-n-b       0.73      0.59      0.65       802
           reggae       0.43      0.40      0.41       806
        reggaeton       0.44      0.42      0.43       801
             rock       0.61      0.51      0.56       795
      rock-n-roll       0.79      0.76      0.77       811
       rockabilly       0.77      0.81      0.79       800
          romance       0.90      0.96      0.93       787
              sad       0.76      0.81      0.78       823
            salsa       0.90      0.97      0.93       826
            samba       0.77      0.79      0.78       811
        sertanejo       0.84      0.90      0.87       812
       show-tunes       0.92      0.88      0.90       802
singer-songwriter       0.45      0.45      0.45       806
              ska       0.73      0.84      0.78       791
            sleep       0.98      0.98      0.98       803
       songwriter       0.42      0.52      0.46       813
             soul       0.68      0.70      0.69       790
          spanish       0.92      0.89      0.90       807
            study       0.95      0.99      0.96       808
          swedish       0.86      0.79      0.82       812
        synth-pop       0.84      0.86      0.85       815
            tango       0.92      0.97      0.94       816
           techno       0.71      0.59      0.64       800
           trance       0.78      0.87      0.82       809
         trip-hop       0.86      0.87      0.86       817
          turkish       0.81      0.91      0.86       815
      world-music       0.86      0.90      0.88       812

         accuracy                           0.78     91199
        macro avg       0.78      0.78      0.78     91199
     weighted avg       0.78      0.78      0.78     91199

In [18]:
ypred_test=main_pipeline.predict(xtest)

In [19]:
print(classification_report(ytest,ypred_test))

                   precision    recall  f1-score   support

         acoustic       0.39      0.36      0.38       213
         afrobeat       0.63      0.60      0.61       203
         alt-rock       0.06      0.06      0.06       215
      alternative       0.12      0.14      0.13       184
          ambient       0.49      0.50      0.49       197
            anime       0.32      0.29      0.30       193
      black-metal       0.71      0.60      0.65       210
        bluegrass       0.61      0.72      0.66       205
            blues       0.23      0.19      0.21       214
           brazil       0.12      0.10      0.11       197
        breakbeat       0.62      0.47      0.54       199
          british       0.29      0.12      0.17       214
         cantopop       0.58      0.58      0.58       193
    chicago-house       0.67      0.46      0.55       206
         children       0.79      0.71      0.75       214
            chill       0.32      0.30      0.31       198
        classical       0.59      0.58      0.58       198
             club       0.69      0.45      0.55       191
           comedy       0.91      0.86      0.88       191
          country       0.65      0.65      0.65       208
            dance       0.42      0.46      0.44       206
        dancehall       0.43      0.30      0.36       204
      death-metal       0.42      0.59      0.49       192
       deep-house       0.17      0.16      0.16       186
   detroit-techno       0.73      0.65      0.69       194
            disco       0.40      0.29      0.34       194
           disney       0.61      0.67      0.64       199
    drum-and-bass       0.73      0.37      0.49       194
              dub       0.09      0.08      0.08       204
          dubstep       0.10      0.07      0.08       226
              edm       0.07      0.07      0.07       200
          electro       0.33      0.23      0.27       207
       electronic       0.30      0.17      0.21       200
              emo       0.32      0.21      0.25       193
             folk       0.23      0.18      0.20       212
            forro       0.56      0.76      0.64       205
           french       0.52      0.27      0.35       194
             funk       0.31      0.18      0.23       218
           garage       0.45      0.28      0.35       192
           german       0.51      0.25      0.33       196
           gospel       0.42      0.41      0.42       212
             goth       0.26      0.35      0.30       223
        grindcore       0.85      0.91      0.88       226
           groove       0.30      0.25      0.27       212
           grunge       0.37      0.42      0.39       202
           guitar       0.43      0.70      0.53       189
            happy       0.39      0.65      0.48       199
        hard-rock       0.22      0.22      0.22       185
         hardcore       0.38      0.46      0.42       205
        hardstyle       0.50      0.78      0.61       210
      heavy-metal       0.58      0.68      0.63       198
          hip-hop       0.38      0.41      0.39       202
       honky-tonk       0.77      0.96      0.85       205
            house       0.15      0.13      0.14       230
              idm       0.40      0.83      0.54       217
           indian       0.21      0.35      0.26       202
            indie       0.07      0.06      0.07       212
        indie-pop       0.03      0.22      0.05       209
       industrial       0.42      0.62      0.50       211
          iranian       0.86      0.97      0.91       181
          j-dance       0.33      0.62      0.43       213
           j-idol       0.77      0.69      0.73       190
            j-pop       0.31      0.16      0.21       224
           j-rock       0.19      0.21      0.20       196
             jazz       0.51      0.46      0.49       213
            k-pop       0.60      0.46      0.52       213
             kids       0.83      0.79      0.81       198
            latin       0.21      0.20      0.21       210
           latino       0.07      0.08      0.07       193
            malay       0.54      0.35      0.43       189
         mandopop       0.56      0.37      0.45       187
            metal       0.03      0.03      0.03       186
        metalcore       0.55      0.48      0.51       206
   minimal-techno       0.46      0.36      0.40       208
              mpb       0.24      0.20      0.22       191
          new-age       0.70      0.59      0.64       199
            opera       0.55      0.38      0.45       189
           pagode       0.49      0.43      0.46       192
            party       0.53      0.52      0.52       205
            piano       0.52      0.43      0.47       197
              pop       0.33      0.27      0.29       166
         pop-film       0.33      0.24      0.28       213
        power-pop       0.63      0.54      0.58       223
progressive-house       0.23      0.19      0.21       191
       psych-rock       0.33      0.17      0.23       196
             punk       0.07      0.05      0.06       221
        punk-rock       0.14      0.14      0.14       192
            r-n-b       0.18      0.11      0.13       198
           reggae       0.04      0.04      0.04       194
        reggaeton       0.05      0.04      0.04       199
             rock       0.26      0.22      0.24       205
      rock-n-roll       0.42      0.43      0.42       189
       rockabilly       0.40      0.33      0.36       200
          romance       0.79      0.80      0.80       213
              sad       0.34      0.36      0.35       177
            salsa       0.63      0.62      0.62       174
            samba       0.38      0.40      0.39       189
        sertanejo       0.58      0.66      0.62       188
       show-tunes       0.53      0.27      0.36       198
singer-songwriter       0.06      0.07      0.06       194
              ska       0.40      0.44      0.42       209
            sleep       0.94      0.79      0.86       197
       songwriter       0.07      0.08      0.07       187
             soul       0.27      0.23      0.25       210
          spanish       0.40      0.29      0.34       193
            study       0.90      0.91      0.90       192
          swedish       0.42      0.26      0.32       188
        synth-pop       0.41      0.41      0.41       185
            tango       0.77      0.72      0.75       184
           techno       0.20      0.12      0.15       200
           trance       0.38      0.31      0.34       191
         trip-hop       0.52      0.45      0.48       183
          turkish       0.45      0.42      0.43       185
      world-music       0.61      0.55      0.58       188

         accuracy                           0.40     22800
        macro avg       0.42      0.40      0.40     22800
     weighted avg       0.42      0.40      0.40     22800